'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class SchoolEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SchoolEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Courses() As DbSet(Of Course)
    Public Property Departments() As DbSet(Of Department)
    Public Property OfficeAssignments() As DbSet(Of OfficeAssignment)
    Public Property OnlineCourses() As DbSet(Of OnlineCourse)
    Public Property OnsiteCourses() As DbSet(Of OnsiteCourse)
    Public Property People() As DbSet(Of Person)
    Public Property StudentGrades() As DbSet(Of StudentGrade)

End Class
